# Use standard Debian-based OpenJDK 17 image (more stable on Windows)
FROM openjdk:21-jdk

# Set working directory
WORKDIR /app

# Copy the built jar into the container
COPY target/Authify-1.0.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the jar
ENTRYPOINT ["java","-jar","app.jar"]
